language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env:
        - TEST_COVERAGE=true

before_install:
  - phpenv config-rm xdebug.ini
  - pecl install pcov
  - composer self-update

install:
  - composer install --no-progress --no-interaction --no-ansi --prefer-dist --no-suggest

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - if [[ "$TEST_COVERAGE" == 'true' ]]; then ./cc-test-reporter before-build ; fi

script:
  - composer run-script test -- --colors=always --coverage-clover ./clover.xml
  - composer run-script analyse -- --no-progress
  - composer run-script cs-check

after_script:
  - |
    if [[ $TEST_COVERAGE == 'true' && $TRAVIS_TEST_RESULT == 0 ]]; then
      echo "Uploading coverage...";
      ./cc-test-reporter format-coverage -t clover -o ./coverage.json ./clover.xml;
      ./cc-test-reporter upload-coverage -i ./coverage.json;
    fi
